if(new URLSearchParams(location.search).has('embedded')){document.body.classList.add('embedded');document.head.insertAdjacentHTML('beforeend','<style>body.embedded .studio-header{display:none}body.embedded .studio-main{padding:26px 22px}body.embedded .tabs,body.embedded .notice{display:none}body.embedded .panel{margin-top:0}.studio-main{font-size:15px}.section-heading h2{font-size:40px}.section-heading p{font-size:14px;line-height:1.7}.form-card label{font-size:11px}.form-card input,.form-card select,.form-card textarea{font-size:14px;padding:13px}.action{font-size:13px;padding:15px 20px}.results{font-size:14px;padding:28px}.results h3{font-size:20px}.results table th{font-size:10px}.results table td{font-size:13px;padding:13px}.results li{font-size:14px}.result-grid b{font-size:10px}.result-grid span{font-size:16px}.notice{font-size:12px}</style>');const reportHeight=()=>parent.postMessage({auraFrameHeight:document.documentElement.scrollHeight},location.origin);new ResizeObserver(reportHeight).observe(document.body);addEventListener('load',reportHeight);setTimeout(reportHeight,50)}
const out=(id,data)=>{const el=document.getElementById(id);if(id==='projectResult'&&typeof data==='object'){el.innerHTML=projectView(data);return}el.textContent=typeof data==='string'?data:JSON.stringify(data,null,2)};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
const risk=n=>`${((n||0)*100).toFixed(1)}%`;
function table(rows, columns){return `<table><thead><tr>${columns.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${c[1](r)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function leaveView(r){return `<h3>Leave impact</h3><div class="result-grid"><b>${r.employee.name}</b><span>${r.leave_period.start_date.slice(0,10)} → ${r.leave_period.end_date.slice(0,10)}</span><b>${r.affected_task_count} affected tasks</b><span>${money(r.revenue_at_risk_inr)} revenue at risk</span><b>SLA risk</b><span>${risk(r.sla_risk_before)} → ${risk(r.sla_risk_after)}</span></div><h3>Affected tasks</h3>${table(r.affected_tasks,[['Task',x=>x.task_id],['Priority',x=>x.priority],['Remaining',x=>`${x.remaining_hours}h`],['Risk',x=>risk(x.risk)]])}<h3>Replacement plan</h3>${table(r.simulated_allocation,[['Task',x=>x.task_id],['Replacement',x=>x.replacement],['Skill match',x=>`${x.skill_match}%`],['SLA risk',x=>risk(x.sla_risk)]])}<h3>Recommended action</h3><p>${r.recommendation}</p><p class="notice">Simulation only — no production changes were made.</p>`}
function projectView(r){return `<h3>Project feasibility — ${r.project_feasibility}</h3><div class="result-grid"><b>Project revenue</b><span>${money(r.revenue_inr)}</span><b>Qualified employees</b><span>${r.qualified_employees}</span><b>Required / qualified capacity</b><span>${r.capacity.required_hours}h / ${r.capacity.available_hours}h</span><b>Predicted completion</b><span>${r.predicted_completion_hours}h</span><b>SLA risk</b><span>${risk(r.sla_breach_probability)}</span><b>Capacity gap</b><span>${r.capacity.capacity_gap}h</span></div><h3>Recommended resources</h3>${table(r.recommended_resources,[['Employee',x=>x.name],['Skill match',x=>`${x.skill_match_score}%`],['Available capacity',x=>`${x.available_capacity_hours}h`],['SLA risk',x=>risk(x.sla_breach_probability)]])}<h3>Business impact</h3><div class="result-grid"><b>Existing revenue at risk</b><span>${money(r.business_impact.existing_revenue_at_risk)}</span><b>Opportunity cost</b><span>${money(r.business_impact.opportunity_cost)}</span></div><h3>Why this decision?</h3><ul>${r.why_this_decision.map(x=>`<li>${x}</li>`).join('')}</ul><p class="notice">Simulation only — no real assignments have been changed.</p>`}
function incidentView(r){return `<h3>${r.scenario.replaceAll('_',' ')}</h3><div class="result-grid"><b>Before</b><span>${r.before.candidate_count} eligible resources · ${risk(r.before.sla_risk)} SLA risk</span><b>After simulation</b><span>${r.after.candidate_count} eligible resources · ${risk(r.after.sla_risk)} SLA risk</span></div><h3>Business impact</h3>${table(r.results||[],[['Metric',x=>x[0]],['Value',x=>x[1]],['Explanation',x=>x[2]]])}<p class="notice">Simulation Mode — No production changes made.</p>`}
async function call(url,body){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.detail||`Request failed (${r.status})`);return x}catch(e){throw new Error(`Unable to complete analysis: ${e.message}`)}}
function openTab(name){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.getElementById(name)?.classList.add('active');history.replaceState(null,'',`#${name}`)}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));
openTab(location.hash.slice(1)||'project');
const future=new Date(Date.now()+72*3600000); document.getElementById('deadline').value=future.toISOString().slice(0,16);document.getElementById('leaveStart').value=new Date().toISOString().slice(0,10);document.getElementById('leaveEnd').value=new Date(Date.now()+2*86400000).toISOString().slice(0,10);
document.getElementById('analyze').onclick=async()=>{out('projectResult','Analyzing workforce…');try{const required_skills=document.getElementById('skills').value.trim().split('\n').filter(Boolean).map(x=>{let [skill,required_level]=x.split(',');if(!skill||!Number(required_level))throw new Error('Enter each required skill as “Skill, level”.');return {skill:skill.trim(),required_level:+required_level}});let r=await call('/api/projects/analyze',{project_name:pname.value,description:pdesc.value,revenue_inr:+revenue.value,estimated_hours:+hours.value,deadline:new Date(deadline.value).toISOString(),priority:priority.value,required_skills,required_employee_count:+count.value,location_requirement:null});out('projectResult',{project_feasibility:r.feasible?'FEASIBLE':'NOT FEASIBLE',revenue_inr:r.revenue_inr,capacity:r.capacity,qualified_employees:r.qualified_resources,predicted_completion_hours:r.predicted_completion_hours,sla_breach_probability:r.sla_breach_probability,recommended_resources:r.recommended_resources,business_impact:{existing_revenue_at_risk:r.existing_revenue_at_risk,opportunity_cost:r.opportunity_cost_inr},why_this_decision:r.reasoning,alternatives:r.alternative_options})}catch(e){out('projectResult',e.message)}};
document.getElementById('leaveAnalyze').onclick=async()=>{out('leaveResult','Running Digital Twin simulation…');try{document.getElementById('leaveResult').innerHTML=leaveView(await call('/api/leave/analyze',{employee_id:leaveEmployee.value,start_date:new Date(leaveStart.value).toISOString(),end_date:new Date(leaveEnd.value).toISOString()}))}catch(e){out('leaveResult',e.message)}};
const scenarios=['single_employee_unavailable','two_employees_unavailable','critical_task_arrives','deadline_shortened','priority_escalation','workforce_capacity_drop','high_value_project_capacity_shortage','skill_bottleneck','workload_spike','multiple_critical_tasks'];document.getElementById('scenarioCards').innerHTML=scenarios.map(s=>`<button class="action" data-s="${s}" style="margin:5px">${s.replaceAll('_',' ')}</button>`).join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=async()=>{out('incidentResult','Running Digital Twin simulation…');try{document.getElementById('incidentResult').innerHTML=incidentView(await call('/api/simulations/'+b.dataset.s,{event_type:b.dataset.s,employee_id:'E002',task_id:'T-101',payload:{employee_ids:['E002','E004']}}))}catch(e){out('incidentResult',e.message)}});
