const $=s=>document.querySelector(s);
const toast=message=>{const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
const profiles={
 'gautam.nair.e001@workforceos.local':{id:'E001',name:'Gautam Nair',role:'AI Engineer',location:'Mumbai',domain:'AI & automation',task:'Model monitoring baseline',meta:'Priority: High · SLA: today, 5:00 PM',progress:62,hours:'5.5',score:'8.3',parts:['8.4','8.7','8.1','8.0'],break:'Tea break · 18 min',leaves:[['7–8 October','Pending review'],['14 September','Approved']],history:[['Model monitoring baseline','In progress','On track','—'],['Forecast validation','17 Sep','Met','8.7 / 10'],['Prompt safety review','9 Sep','Met','8.5 / 10']]},
 'rohan.srinivasan.e002@workforceos.local':{id:'E002',name:'Rohan Srinivasan',role:'Data Analyst',location:'Coimbatore',domain:'Data intelligence',task:'Customer churn analysis',meta:'Priority: High · SLA: tomorrow, 12:00 PM',progress:54,hours:'5.0',score:'8.1',parts:['8.2','8.4','7.7','8.0'],break:'Meal break · 24 min',leaves:[['24–26 September','Pending review'],['12–13 August','Approved'],['5 July','Not approved · coverage unavailable']],history:[['Customer churn analysis','In progress','On track','—'],['Warehouse trend audit','18 Sep','Met','8.6 / 10'],['Reporting export','4 Sep','Delayed 1.2h','8.0 / 10']]},
 'divya.singh.e004@workforceos.local':{id:'E004',name:'Divya Singh',role:'Data Engineer',location:'Chennai',domain:'Data platform',task:'Warehouse pipeline optimisation',meta:'Priority: Medium · SLA: Friday, 3:00 PM',progress:73,hours:'6.5',score:'8.8',parts:['8.9','9.0','8.3','8.5'],break:'No active break',leaves:[['1 October','Pending review'],['2 September','Approved']],history:[['Warehouse pipeline optimisation','In progress','On track','—'],['Customer data cleanup','16 Sep','Met','9.1 / 10'],['ETL reliability patch','8 Sep','Met','8.9 / 10']]},
 'swati.mehta.e005@workforceos.local':{id:'E005',name:'Swati Mehta',role:'DevOps Engineer',location:'Bengaluru',domain:'Cloud reliability',task:'Kubernetes cost controls',meta:'Priority: Medium · SLA: Friday, 11:00 AM',progress:81,hours:'4.0',score:'8.7',parts:['9.0','8.8','8.9','8.0'],break:'Stretch break · 12 min',leaves:[['19 September','Approved']],history:[['Kubernetes cost controls','In progress','On track','—'],['Production deployment','15 Sep','Met','9.0 / 10'],['Backup verification','6 Sep','Met','8.6 / 10']]},
 'ishita.gupta.e010@workforceos.local':{id:'E010',name:'Ishita Gupta',role:'Security Specialist',location:'Bengaluru',domain:'Security operations',task:'Identity access review',meta:'Priority: High · SLA: today, 6:00 PM',progress:69,hours:'6.0',score:'8.2',parts:['8.3','8.6','7.8','8.0'],break:'No active break',leaves:[['3–4 October','Pending review'],['8 August','Approved']],history:[['Identity access review','In progress','On track','—'],['Vulnerability scan','17 Sep','Met','8.8 / 10'],['Access policy update','10 Sep','Met','8.3 / 10']]},
 'siddharth.patel.e012@workforceos.local':{id:'E012',name:'Siddharth Patel',role:'Software Developer',location:'Mumbai',domain:'Application engineering',task:'Payment API reconciliation',meta:'Priority: High · SLA: today, 4:30 PM',progress:67,hours:'6.0',score:'9.0',parts:['9.4','8.9','8.2','8.0'],break:'Meal break · 26 min',leaves:[['24–26 September','Pending review'],['12–13 August','Approved']],history:[['Payment API reconciliation','In progress','On track','—'],['Customer profile migration','18 Sep','Met','9.2 / 10'],['Auth service hotfix','11 Sep','Met','8.8 / 10']]},
 'priya.nair.e025@workforceos.local':{id:'E025',name:'Priya Nair',role:'Security Specialist',location:'Hyderabad',domain:'Security engineering',task:'Incident response playbook',meta:'Priority: Critical · SLA: today, 3:00 PM',progress:75,hours:'6.5',score:'8.9',parts:['9.2','8.8','8.4','8.0'],break:'No active break',leaves:[['10 October','Pending review'],['19 August','Approved']],history:[['Incident response playbook','In progress','On track','—'],['Credential rotation','18 Sep','Met','9.1 / 10'],['Threat model update','7 Sep','Met','8.7 / 10']]}
};
let activeProfile,breakTimer;
document.addEventListener('DOMContentLoaded',()=>{const button=$('#endBreak');if(button)button.textContent='Stop break'});
async function api(url, body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||`Request failed (${r.status})`);return data}
function renderProfile(p){activeProfile=p;$('#employeeId').textContent=p.id;$('#employeeName').textContent=p.name;$('#employeeMeta').textContent=`${p.id} · ${p.role} · ${p.location} · ${p.domain}`;$('#taskTitle').textContent=p.task;$('#taskMeta').textContent=p.meta;$('#taskProgress').style.width=`${p.progress}%`;$('#taskProgressText').textContent=`${p.progress}% complete`;$('#focusHours').innerHTML=`${p.hours}<span>h</span>`;$('#performanceScore').innerHTML=`${p.score}<span>/10</span>`;['slaScore','qualityScore','availabilityScore','policyRecord'].forEach((id,i)=>$('#'+id).textContent=p.parts[i]);$('#lastBreak').textContent=p.break;$('#leaveList').innerHTML=p.leaves.map(([date,state])=>`<div><span>${date}</span><b class="${state.includes('Pending')?'pending':state.includes('Approved')?'approved':'denied'}">${state}</b></div>`).join('');$('#historyRows').innerHTML=`<div class="history-row heading"><span>Task</span><span>Completion</span><span>SLA</span><span>Quality</span></div>${p.history.map(([task,done,sla,quality])=>`<div class="history-row"><span>${task}</span><span>${done}</span><span class="${sla.includes('Delayed')?'watch':'good'}">${sla}</span><span>${quality}</span></div>`).join('')}`;$('#notificationItems').innerHTML=`<article><b>Current SLA</b><p>${p.task} is ${p.progress}% complete and on track.</p></article><article><b>Leave request</b><p>${p.leaves[0][0]} is ${p.leaves[0][1].toLowerCase()}.</p></article><article><b>Break check-ins</b><p>Respond when prompted after a 30-minute active break.</p></article>`}
function openEmployee(email){const p=profiles[email];if(!p){toast('Use one of the listed local employee accounts for this demo.');return}sessionStorage.setItem('workforceosUser',JSON.stringify({email,role:'employee',employeeId:p.id}));renderProfile(p);$('#login').hidden=true;$('#portal').hidden=false;toast(`${p.role} workspace opened.`)}
$('#accessForm').addEventListener('submit',e=>{e.preventDefault();const email=$('#email').value.trim().toLowerCase(),role=$('#role').value,password=$('#password').value;if(role==='manager'){if(email!=='manager.demo@workforceos.local'||password!=='manager123'){toast('Use manager.demo@workforceos.local with the manager demo password.');return}sessionStorage.setItem('workforceosUser',JSON.stringify({email,role:'manager'}));window.location.href='index.html';return}if(password!=='employee123'){toast('Incorrect demo password. Use employee123 for employee accounts.');return}openEmployee(email)});
$('#demoAccounts').addEventListener('click',e=>{const b=e.target.closest('[data-email]');if(b){$('#email').value=b.dataset.email;$('#role').value='employee'}});
$('#signOut').addEventListener('click',()=>{clearTimeout(breakTimer);sessionStorage.removeItem('workforceosUser');$('#portal').hidden=true;$('#login').hidden=false;$('#email').value=''});
function showBreakCheck(){$('#status').textContent='Check-in required';$('#breakState').textContent='30-minute response required';$('#breakCheck').hidden=false;$('#notifications').hidden=false;$('#notificationBadge').textContent='3'}
function registerOverdueBreak(){$('#status').textContent='Break overdue';$('#breakState').textContent='Policy flag recorded · manager review required';$('#performanceScore').innerHTML=`${Math.max(1,Number(activeProfile.score)-.3).toFixed(1)}<span>/10</span>`;$('#policyRecord').textContent='7.0';$('#notifications').hidden=false;$('#notificationBadge').textContent='4';toast('Break check was not answered. Management has been notified for coverage review.')}
async function endBreak(){try{await api('/api/break/end',{employee_id:activeProfile.id});clearTimeout(breakTimer);$('#status').textContent='Working';$('#breakState').textContent='Break ended · response recorded';$('#breakCheck').hidden=true;$('#startBreak').hidden=false;$('#endBreak').hidden=true;toast('Break ended and availability restored.')}catch(e){toast(e.message)}}
$('#startBreak').addEventListener('click',async()=>{try{await api('/api/break/start',{employee_id:activeProfile.id,break_type:'SHORT_BREAK'});$('#status').textContent='On break';$('#breakState').textContent='Active break · check-in due at 30 min';$('#breakCheck').hidden=true;$('#startBreak').hidden=true;$('#endBreak').hidden=false;clearTimeout(breakTimer);breakTimer=setTimeout(()=>{showBreakCheck();breakTimer=setTimeout(registerOverdueBreak,300000)},1800000);toast('Break started. Use End break when you return.')}catch(e){toast(e.message)}});
$('#endBreak').addEventListener('click',endBreak);
$('#resume').addEventListener('click',endBreak);
$('#extend').addEventListener('click',()=>{$('#breakState').textContent='Extension requested · manager notified';toast('Extension request recorded. Management will receive the coverage alert.')});
$('#showNotifications').addEventListener('click',async()=>{const panel=$('#notifications');panel.hidden=!panel.hidden;if(!panel.hidden){$('#notificationBadge').textContent='0';try{await api('/api/notifications/read',{})}catch(e){toast(e.message)}}});
$('#leaveForm').addEventListener('submit',async e=>{e.preventDefault();try{const start=$('#leaveStart').value,end=$('#leaveEnd').value;if(!start||!end)throw new Error('Select both leave dates.');const result=await api('/api/leave/request',{employee_id:activeProfile.id,start_date:new Date(start).toISOString(),end_date:new Date(end).toISOString()});activeProfile.leaves.unshift([`${start} → ${end}`,'Pending review']);renderProfile(activeProfile);toast(result.analysis?.simulation_only?'Leave request sent; coverage impact simulated.':'Leave request sent.')}catch(e){toast(e.message)}});
$('#demoAccounts').innerHTML=Object.entries(profiles).map(([email,p])=>`<button type="button" data-email="${email}"><b>${p.name}</b><span>${p.id} · ${p.role}</span></button>`).join('');
const saved=JSON.parse(sessionStorage.getItem('workforceosUser')||'null');if(saved?.role==='employee'&&profiles[saved.email])openEmployee(saved.email);
